/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg2048;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Aedamantium
 */
public class _2048 extends javax.swing.JFrame {
    
    
      JLabel [][] label = new JLabel[4][4];
      ArrayList<JLabel> labelList = new ArrayList<>();
      ArrayList<JPanel> panelList = new ArrayList<>();
      
      static ArrayList<String[][]> geriListTutucu = new ArrayList<>();
    /**
     * Creates new form _2048
     */
    public _2048() {
        initComponents();
        Methods_2048 m = new Methods_2048();    
        
        
        
        label [0][0] = ss; label [0][1] = sb; label [0][2] = si; label [0][3] = su;
        label [1][0] = bs; label [1][1] = bb; label [1][2] = bi; label [1][3] = bu;
        label [2][0] = is; label [2][1] = ib; label [2][2] = ii; label [2][3] = iu;
        label [3][0] = us; label [3][1] = ub; label [3][2] = ui; label [3][3] = uu;
        
        labelList.add(ss);
        labelList.add(sb);
        labelList.add(si);
        labelList.add(su);
        labelList.add(bs);
        labelList.add(bb);
        labelList.add(bi);
        labelList.add(bu);
        labelList.add(is);
        labelList.add(ib);
        labelList.add(ii);
        labelList.add(iu);
        labelList.add(us);
        labelList.add(ub);
        labelList.add(ui);
        labelList.add(uu);        
        panelList.add(jPanel1);
        panelList.add(jPanel2);
        panelList.add(jPanel3);
        panelList.add(jPanel4);
        panelList.add(jPanel5);
        panelList.add(jPanel6);
        panelList.add(jPanel7);
        panelList.add(jPanel8);
        panelList.add(jPanel9);
        panelList.add(jPanel10);
        panelList.add(jPanel11);
        panelList.add(jPanel12);
        panelList.add(jPanel13);
        panelList.add(jPanel14);
        panelList.add(jPanel15);
        panelList.add(jPanel16);
        jDialog1.setLocation(this.getLocation());
        m.sayilariDagit(labelList);
        m.renkleriBelirle(panelList, labelList);        
        String satir = m.rekoruOku();
        best.setText(satir);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        ss = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        sb = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        si = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        su = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        bs = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        bb = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        bi = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        bu = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        is = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        ib = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        ii = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        iu = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        us = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        ub = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        ui = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        uu = new javax.swing.JLabel();
        tekrar = new javax.swing.JButton();
        puan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        best = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        geri = new javax.swing.JButton();

        jDialog1.setMinimumSize(new java.awt.Dimension(190, 130));

        jLabel4.setText("OYUN BİTTİ! TEKRAR OYNA");

        jButton1.setText("Evet");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Hayır");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jDialog1.setLocation(this.getLocation());

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setMinimumSize(new java.awt.Dimension(280, 412));
        setPreferredSize(new java.awt.Dimension(280, 412));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(50, 50));

        ss.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ss.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ss.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(ss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ss, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 114, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(50, 50));

        sb.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        sb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sb.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(sb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 114, -1, -1));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setPreferredSize(new java.awt.Dimension(50, 50));

        si.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        si.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        si.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(si, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(si, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 114, -1, -1));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setPreferredSize(new java.awt.Dimension(50, 50));

        su.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        su.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        su.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(su, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(su, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 114, -1, -1));

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setPreferredSize(new java.awt.Dimension(50, 50));

        bs.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bs.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(bs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 171, -1, -1));

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel6.setPreferredSize(new java.awt.Dimension(50, 50));

        bb.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bb.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(bb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 171, -1, -1));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setPreferredSize(new java.awt.Dimension(50, 50));

        bi.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bi.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(bi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 171, -1, -1));

        jPanel8.setBackground(new java.awt.Color(153, 153, 153));
        jPanel8.setPreferredSize(new java.awt.Dimension(50, 50));

        bu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bu.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(bu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 171, -1, -1));

        jPanel9.setBackground(new java.awt.Color(153, 153, 153));
        jPanel9.setPreferredSize(new java.awt.Dimension(50, 50));

        is.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        is.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        is.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(is, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(is, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 228, -1, -1));

        jPanel10.setBackground(new java.awt.Color(153, 153, 153));
        jPanel10.setPreferredSize(new java.awt.Dimension(50, 50));

        ib.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ib.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ib.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ib, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 228, -1, -1));

        jPanel11.setBackground(new java.awt.Color(153, 153, 153));
        jPanel11.setPreferredSize(new java.awt.Dimension(50, 50));

        ii.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ii.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ii.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ii, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ii, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 228, -1, -1));

        jPanel12.setBackground(new java.awt.Color(153, 153, 153));
        jPanel12.setPreferredSize(new java.awt.Dimension(50, 50));

        iu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        iu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iu.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(iu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 228, -1, -1));

        jPanel13.setBackground(new java.awt.Color(153, 153, 153));
        jPanel13.setPreferredSize(new java.awt.Dimension(50, 50));

        us.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        us.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        us.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(us, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(us, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 285, -1, -1));

        jPanel14.setBackground(new java.awt.Color(153, 153, 153));
        jPanel14.setPreferredSize(new java.awt.Dimension(50, 50));

        ub.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ub.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ub.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ub, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 285, -1, -1));

        jPanel15.setBackground(new java.awt.Color(153, 153, 153));
        jPanel15.setPreferredSize(new java.awt.Dimension(50, 50));

        ui.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ui.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ui.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(ui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ui, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 285, -1, -1));

        jPanel16.setBackground(new java.awt.Color(153, 153, 153));
        jPanel16.setPreferredSize(new java.awt.Dimension(50, 50));

        uu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        uu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uu.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(uu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 285, -1, -1));

        tekrar.setText("Tekrar");
        tekrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tekrarActionPerformed(evt);
            }
        });
        tekrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tekrarKeyPressed(evt);
            }
        });
        getContentPane().add(tekrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        puan.setEditable(false);
        puan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        puan.setText("0");
        puan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                puanKeyPressed(evt);
            }
        });
        getContentPane().add(puan, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 13, 64, -1));

        jLabel1.setText("PUAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        best.setEditable(false);
        best.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        best.setText("0");
        best.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bestKeyPressed(evt);
            }
        });
        getContentPane().add(best, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 42, 64, -1));

        jLabel2.setText("EN İYİ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("2048");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 123, 56));

        geri.setText("Geri");
        geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriActionPerformed(evt);
            }
        });
        geri.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                geriKeyPressed(evt);
            }
        });
        getContentPane().add(geri, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tekrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tekrarActionPerformed
        // TODO add your handling code here:    
        puan.setText("0");
        Methods_2048 m = new Methods_2048();        
        for (int i = 0; i < labelList.size(); i++) {
            labelList.get(i).setText("");
        }
        m.sayilariDagit(labelList);
        m.renkleriBelirle(panelList, labelList);
        geriListTutucu.clear();
    }//GEN-LAST:event_tekrarActionPerformed

    private void geriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriActionPerformed
        Methods_2048 m = new Methods_2048();
        if (!geriListTutucu.isEmpty()) {
            for (int i = 0; i < label.length; i++) {
                for (int j = 0; j < label[i].length; j++) {
                    label[i][j].setText(geriListTutucu.get(geriListTutucu.size() - 1)[i][j]);
                }
            }
            geriListTutucu.remove(geriListTutucu.size() - 1);
        }
        m.renkleriBelirle(panelList, labelList);
    }//GEN-LAST:event_geriActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jDialog1.setVisible(false);
        Methods_2048 m = new Methods_2048();        
        for (int i = 0; i < labelList.size(); i++) {
            labelList.get(i).setText("");
        }
        m.sayilariDagit(labelList);
        m.renkleriBelirle(panelList, labelList);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jDialog1.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void puanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_puanKeyPressed
        // TODO add your handling code here:
        Methods_2048 m = new Methods_2048();  
        String[][] geriList = new String[4][4];
        for (int i = 0; i < label.length; i++) {
            for (int j = 0; j < label[i].length; j++) {
                geriList[i][j] = label[i][j].getText();
            }
        }
       
            geriListTutucu.add(geriList);
        
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            m.yukari(label,panelList,labelList);            
        } 
        else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
           m.asagi(label,panelList,labelList);  
        }
        else if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
           m.saga(label,panelList,labelList); 
        }
        else if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
           m.sola(label,panelList,labelList);  
        }
        if (Integer.parseInt(puan.getText()) > Integer.parseInt(best.getText())) {
            _2048.best.setText(_2048.puan.getText());
            m.rekoruYaz(_2048.best.getText());
        }
        jDialog1.setVisible(m.bittiMi(label));  
        
    }//GEN-LAST:event_puanKeyPressed

    private void bestKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bestKeyPressed
        // TODO add your handling code here:
        Methods_2048 m = new Methods_2048();     
        String[][] geriList = new String[4][4];
        for (int i = 0; i < label.length; i++) {
            for (int j = 0; j < label[i].length; j++) {
                geriList[i][j] = label[i][j].getText();
            }
        }
            geriListTutucu.add(geriList);
        
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            m.yukari(label,panelList,labelList);            
        } 
        else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
           m.asagi(label,panelList,labelList);  
        }
        else if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
           m.saga(label,panelList,labelList); 
        }
        else if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
           m.sola(label,panelList,labelList);  
        }
        if (Integer.parseInt(puan.getText()) > Integer.parseInt(best.getText())) {
            _2048.best.setText(_2048.puan.getText());
            m.rekoruYaz(_2048.best.getText());
        }
        JOptionPane.showMessageDialog(this,"OYUN BITTI TEKRAR OYNA?");
        //jDialog1.setVisible(m.bittiMi(label));  
    }//GEN-LAST:event_bestKeyPressed

    private void tekrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tekrarKeyPressed
        // TODO add your handling code here:
        Methods_2048 m = new Methods_2048();      
        String[][] geriList = new String[4][4];
        for (int i = 0; i < label.length; i++) {
            for (int j = 0; j < label[i].length; j++) {
                geriList[i][j] = label[i][j].getText();
            }
        }
            geriListTutucu.add(geriList);
            
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            m.yukari(label,panelList,labelList);            
        } 
        else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
           m.asagi(label,panelList,labelList);  
        }
        else if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
           m.saga(label,panelList,labelList); 
        }
        else if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
           m.sola(label,panelList,labelList);  
        }
        if (Integer.parseInt(puan.getText()) > Integer.parseInt(best.getText())) {
            _2048.best.setText(_2048.puan.getText());
            m.rekoruYaz(_2048.best.getText());
        }
        jDialog1.setVisible(m.bittiMi(label));  
    }//GEN-LAST:event_tekrarKeyPressed

    private void geriKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_geriKeyPressed
        // TODO add your handling code here:
        Methods_2048 m = new Methods_2048();     
        String[][] geriList = new String[4][4];
        for (int i = 0; i < label.length; i++) {
            for (int j = 0; j < label[i].length; j++) {
                geriList[i][j] = label[i][j].getText();
            }
        }
            geriListTutucu.add(geriList);
        
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            m.yukari(label,panelList,labelList);            
        } 
        else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
           m.asagi(label,panelList,labelList);  
        }
        else if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
           m.saga(label,panelList,labelList); 
        }
        else if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
           m.sola(label,panelList,labelList);  
        }
        if (Integer.parseInt(puan.getText()) > Integer.parseInt(best.getText())) {
            _2048.best.setText(_2048.puan.getText());
            m.rekoruYaz(_2048.best.getText());
        }
        jDialog1.setVisible(m.bittiMi(label));  
    }//GEN-LAST:event_geriKeyPressed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(_2048.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(_2048.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(_2048.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(_2048.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new _2048().setVisible(true);
            }
        });
    }
    
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bb;
    public static javax.swing.JTextField best;
    private javax.swing.JLabel bi;
    private javax.swing.JLabel bs;
    private javax.swing.JLabel bu;
    private javax.swing.JButton geri;
    private javax.swing.JLabel ib;
    private javax.swing.JLabel ii;
    private javax.swing.JLabel is;
    private javax.swing.JLabel iu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    public static javax.swing.JTextField puan;
    private javax.swing.JLabel sb;
    private javax.swing.JLabel si;
    private javax.swing.JLabel ss;
    private javax.swing.JLabel su;
    private javax.swing.JButton tekrar;
    private javax.swing.JLabel ub;
    private javax.swing.JLabel ui;
    private javax.swing.JLabel us;
    private javax.swing.JLabel uu;
    // End of variables declaration//GEN-END:variables
}
